name: Spring Boot CI

on: [push, pull_request]

jobs:

    test-8:
        name: Unit & Integration Tests on Java 8
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Maven Install
              run: mvn -B clean install
            - name: Maven Verify
              run: mvn -B clean verify

    test-13:
        name: Unit & Integration Tests on Java 13
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 13
              uses: actions/setup-java@v1
              with:
                  java-version: 1.13
            - name: Maven Install
              run: mvn -B clean install
            - name: Maven Verify
              run: mvn -B clean verify
